#!/bin/bash

display_usage() {
    echo ""
    echo "*******************************************************************************"
    echo "* gamdisplay: Script automatically works out which GAMMA display command to   *"
    echo "*             run based on the input file/s. Works with files with            *"
    echo "*             extensions:                                                     *"
    echo "*                                                                             *"
    echo "*             *.mli, *_eqa.mli                                                *" 
    echo "*             *.slc, *_eqa.slc                                                *"
    echo "*             *.dem, *_rdc.dem                                                *"
    echo "*             *_rdc.sim, *_eqa.sim                                            *"
    echo "*             *_sar.flt                                                       *"
    echo "*             *_init.sar, *_lsat.sar                                          *"
    echo "*             *.lt                                                            *"
    echo "*             *.cc, *_eqa.cc                                                  *"
    echo "*             *.flag, *_eqa.flag                                              *"
    echo "*             *.ras, *_eqa.ras                                                *"
    echo "*             *.int, *_eqa.int                                                *"
    echo "*             *.unw, *_sim.unw, *_eqa.unw                                     *"
    echo "*                                                                             *"
    echo "* input:   [file_1]   name of file to display                                 *"
    echo "*          <file_2>   name of second file to display (optional)               *"
    echo "*          <start>    starting line of SLC (optional, default: 1)             *"
    echo "*          <nlines>   number of lines to display (optional, default 4000      *"
    echo "*                     for large files)                                        *"
    echo "*                                                                             *"
    echo "* author: Sarah Lawrie @ GA       22/04/2015, v1.0                            *"
    echo "*         Sarah Lawrie @ GA       16/10/2015, v1.1                            *"
    echo "*              - added ability to view dem landsat images                     *"
    echo "*         Sarah Lawrie @ GA       13/08/2018, v2.0                            *"
    echo "*             -  Major update to streamline processing:                       *"
    echo "*                  - use functions for variables and PBS job generation       *"
    echo "*                  - add option to auto calculate multi-look values and       *"
    echo "*                      master reference scene                                 *"
    echo "*                  - add initial and precision baseline calculations          *"
    echo "*                  - add full Sentinel-1 processing, including resizing and   *"
    echo "*                     subsetting by bursts                                    *"
    echo "*                  - remove GA processing option                              *"
    echo "*******************************************************************************"
    echo -e "Usage: gamdisplay [file_1] <file_2> <start> <nlines>"
    }

if [ $# -lt 1 ]
then 
    display_usage
    exit 1
fi

file1=$1

if [ $# -eq 2 ]; then
    file2=$2
fi


# determine proc file path
cur_path=`pwd`
cur_dir=$(basename "$cur_path")

# if in a date directory
if [[ $cur_dir =~ ^[0-9-]+$ ]]; then
    proc1=`dirname $cur_path`
    proc=`dirname $proc1`
    proc_file=$proc.proc
# if in a main directory (eg. SLC, DEM, INT)
elif [ $cur_dir ==  SLC -o $cur_dir == DEM -o $cur_dir == INT ]; then
    proc=`dirname $cur_path`
    proc_file=$proc.proc
# if in track directory
elif [[ $cur_dir == T* ]]; then
    proc1=`dirname $cur_path`
    proc=$proc1/$cur_dir
    proc_file=$proc.proc
# if in GAMMA directory
elif [ $cur_dir == GAMMA ]; then
    proc1=`dirname $cur_path`
    proc=`ls -d $cur_path/T????`
    proc_file=$proc.proc
fi


##########################   GENERIC SETUP  ##########################

# Load generic GAMMA functions
source ~/repo/gamma_insar/gamma_functions

# Load variables and directory paths
proc_variables $proc_file
final_file_loc

# Load GAMMA to access GAMMA programs
source $config_file

######################################################################


if [ $cur_dir == 'DEM' ]; then
    proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
else
    path=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    dir=$(basename "$path")
    if [ $dir == 'SLC' ]; then
        proj_dir=`echo $path | sed 's,/*[^/]\+/*$,,'`
    elif [ $dir == 'INT' ]; then
        proj_dir=`echo $path | sed 's,/*[^/]\+/*$,,'`
    fi
fi


# Identify file extension
file1_ext=`echo $file1 | awk -F . '{if (NF>1) {print $NF}}'`
file2_ext=`echo $file2 | awk -F . '{if (NF>1) {print $NF}}'`

# Display MLI (*.mli, *_eqa.mli)
if [ $file1_ext == mli ]; then
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    mli_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $mli_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.mli files 
	if [ -z $file2_ext ]; then # if no second file
	    width1=`grep range_samples: $file1.par | awk '{print $2}'`
	    lines=`grep azimuth_lines: $file1.par | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width1=`grep range_samples: $file1.par | awk '{print $2}'` 
	    width2=`grep range_samples: $file2.par | awk '{print $2}'`
	    lines1=`grep azimuth_lines: $file1.par | awk '{print $2}'`
	    lines2=`grep azimuth_lines: $file2.par | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
     fi
else
    :
fi


# Display SLC (*.slc)
if [ $file1_ext == slc ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,' | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    slc_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=0rlks
    lks2=0rlks
    if [ $slc_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
     else # *.slc files
	if [ -z $file2_ext ]; then # if no second file
	    width1=`grep range_samples: $file1.par | awk '{print $2}'`
	    format1=`grep image_format: $file1.par | awk '{print $2}'`
	    if [ $format1 == FCOMPLEX ]; then
		type=0
	    else
		type=1 # for SCOMPLEX
	    fi
	    lines=`grep azimuth_lines: $file1.par | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disSLC $file1 $width1 $start $nlines - - $type
	else # two files
	    width1=`grep range_samples: $file1.par | awk '{print $2}'`
	    width2=`grep range_samples: $file2.par | awk '{print $2}'`
	    format1=`grep image_format: $file1.par | awk '{print $2}'`
	    format2=`grep image_format: $file2.par | awk '{print $2}'`
	    if [ $format1 == FCOMPLEX -a $format2 == FCOMPLEX ]; then
		type=0
	    else
		type=1 # for SCOMPLEX
	    fi
	    lines1=`grep azimuth_lines: $file1.par | awk '{print $2}'`
	    lines2=`grep azimuth_lines: $file2.par | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2SLC $file1 $file2 $width1 $width2 $start $nlines - - - - $type
	fi
    fi
else
    :
fi

# Display DEM files (*.dem, *rdc.dem, *eqa.dem, *.lt, *.sim)
if [ $file1_ext == dem ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    dem_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $dem_type == rdc ]; then
    if [ -z $file2_ext ]; then # if no second file
	width_file=$proj_dir/DEM/"diff"*$lks1.par
	width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	dishgt $file1 - $width1 $start - $nlines - - -
    else # two files
	width_file1=$proj_dir/DEM/"diff"*$lks1.par
	width_file2=$proj_dir/DEM/"diff"*$lks2.par
	width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	if [ "$lines1" -gt "$lines2" ]; then
	    lines=$lines1
	else
	    lines=$lines2
	fi
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	dis2hgt $file1 $file2 $width1 $width2 $start $nlines
    fi
    elif [ $dem_type == eqa ]; then
	lines=`grep nlines: $file1.par | awk '{print $2}'`
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	disdem_par $file1 $file1.par $start $nlines - - -
    else # .dem files
	lines=`grep nlines: $file1.par | awk '{print $2}'`
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	disdem_par $file1 $file1.par $start $nlines - - - 
    fi
else
    :
fi
if [ $file1_ext == lt ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    dem_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ -z $file2_ext ]; then # if no second file
	width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	width1=`grep width: $width_file | awk '{print $2}'`
	lines=`grep nlines: $width_file | awk '{print $2}'`
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	dismph $file1 $width1 $start $nlines - - 0
    else # two files
	width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	width1=`grep width: $width_file1 | awk '{print $2}'`
	width2=`grep width: $width_file2 | awk '{print $2}'`
	lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	if [ "$lines1" -gt "$lines2" ]; then
	    lines=$lines1
	else
	    lines=$lines2
	fi
	if [ $# -lt 4 -a $lines -gt 4000 ]; then
	    echo  " "
	    echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
	    echo  " "
	    start=1
	    nlines=4000
	elif [ $# -eq 4 -a $lines -gt 4000 ]; then
	    start=$3
	    nlines=$4
	else
	    start=1
	    nlines=-
	fi
	dis2mph $file1 $file2 $width1 $width2 $start $nlines - - - -
    fi
else
    :
fi
if [ $file1_ext == sim ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    dem_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $dem_type == rdc ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
    elif [ $dem_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
    else
	:
    fi
else
    :
fi

# Display landsat float files (from dem coregistration)
if [ $file1_ext == flt ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    dem_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $dem_type == sar ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
    else
	:
    fi
else
    :
fi


# Display landsat dem files (from dem coregistration)
#*_init.sar, *_lsat.sar    




if [ $file1_ext == sar ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    dem_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $dem_type == init ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
    elif [ $dem_type == lsat ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dispwr $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2pwr $file1 $file2 $width1 $width2 $start $nlines - - - - 0
	fi
    else
	:
    fi
else
    :
fi


# Display coherence file (*.cc)
if [ $file1_ext == cc ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,' | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    cc_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $cc_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.cc files
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    discc $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2cc $file1 $file2 $width1 $width2 $start $nlines - - - -    
	fi
    fi
else
    :
fi

# Display flag file (*.flag, *_eqa.flag)
if [ $file1_ext == flag ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,' | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    flag_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $flag_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.flag files
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disflag $file1 $width1 $start $nlines
	else # no second file option
	    :
	fi
    fi
else
    :
fi

# Display raster files (*.ras)
if [ $file1_ext == ras ]; then
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    ras_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $ras_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.ras files 
	if [ -z $file2_ext ]; then # if no second file
	    disras $file1 - -
	else # two files
	    dis2ras $file1 $file2 - -
	fi
    fi
else
    :
fi

# Display interferogram (*.int)
if [ $file1_ext == int ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,' | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    int_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $int_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.int files 
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dismph $file1 $width1 $start $nlines - - 0
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2mph $file1 $file2 $width1 $width2 $start $nlines - - - -    
	fi
    fi
else
    :
fi

# Display unwrapped interferograms (*.unw)
if [ $file1_ext == unw ]; then
    #proj_dir=`echo $PWD | sed 's,/*[^/]\+/*$,,' | sed 's,/*[^/]\+/*$,,'`
    file_name1=`echo $file1 | cut -d'.' -f1`
    file_name2=`echo $file2 | cut -d'.' -f1`
    unw_type=`echo $file_name1 | sed 's#.*_##'`
    lks1=`echo $file_name1 | awk -F _ '{print $3}'`
    lks2=`echo $file_name2 | awk -F _ '{print $3}'`
    if [ $unw_type == sim ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    elif [ $unw_type == eqa ]; then
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width1=`grep width: $width_file | awk '{print $2}'`
	    lines=`grep nlines: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/*$lks1"_eqa.dem.par"
	    width_file2=$proj_dir/DEM/*$lks2"_eqa.dem.par"
	    width1=`grep width: $width_file1 | awk '{print $2}'`
	    width2=`grep width: $width_file2 | awk '{print $2}'`
	    lines1=`grep nlines: $width_file1 | awk '{print $2}'`
	    lines2=`grep nlines: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    else # *.unw files 
	if [ -z $file2_ext ]; then # if no second file
	    width_file=$proj_dir/DEM/"diff"*$lks1.par
	    width1=`grep range_samp_1: $width_file | awk '{print $2}'`
	    lines=`grep az_samp_1: $width_file | awk '{print $2}'`
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    disrmg $file1 - $width1 $start - $nlines - - - -
	else # two files
	    width_file1=$proj_dir/DEM/"diff"*$lks1.par
	    width_file2=$proj_dir/DEM/"diff"*$lks2.par
	    width1=`grep range_samp_1: $width_file1 | awk '{print $2}'`
	    width2=`grep range_samp_1: $width_file2 | awk '{print $2}'`
	    lines1=`grep az_samp_1: $width_file1 | awk '{print $2}'`
	    lines2=`grep az_samp_1: $width_file2 | awk '{print $2}'`
	    if [ "$lines1" -gt "$lines2" ]; then
		lines=$lines1
	    else
		lines=$lines2
	    fi
	    if [ $# -lt 4 -a $lines -gt 4000 ]; then
		echo  " "
		echo "Image length is "$lines", auto setting length to 4000 lines. If different length required, enter no. lines."
		echo  " "
		start=1
		nlines=4000
	    elif [ $# -eq 4 -a $lines -gt 4000 ]; then
		start=$3
		nlines=$4
	    else
		start=1
		nlines=-
	    fi
	    dis2rmg $file1 $file2 $width1 $width2 $start $nlines - - - - 
	fi
    fi
else
    :
fi


# script end
####################