#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l mem=5GB
#PBS -l ncpus=1
#PBS -l wd
#PBS -lother=gdata1
#PBS -q normal

source /home/547/mcg547/dg9-apps/GAMMA/GAMMA_CONFIG_bash

## enter GAMMA code from command.log below

