#!/bin/bash

display_usage() {
    echo ""
    echo "*******************************************************************************"
    echo "* view_unw: Script to quick view unwrapped interferogram (not geocoded).      *"
    echo "*                                                                             *"
    echo "* input:   [unw_ifg]  name of file to display (*.unw)                         *"
    echo "*                                                                             *"
    echo "* author: Sarah Lawrie @ GA       07/03/2015, v1.0                            *"
    echo "*******************************************************************************"
    echo -e "Usage: view_unw [unw_ifg]"
    }

if [ $# -lt 1 ]
then 
    display_usage
    exit 1
fi

file=$1
width_file=*diff.par
width=`grep range_samp_1: $width_file | awk '{print $2}'`
file2=`echo $file | cut -d'.' -f1`
bmp=$file2.bmp

rasrmg $file - $width 1 1 0 1 1 0.33333 1 0.35 0 1 $bmp
mogrify -resize 800x800 $bmp
display $bmp
rm -rf $bmp



