##### GAMMA CONFIGURATION FILE #####

STACK_ID=Fake Unit Testing Stack

LAND_CENTER = -37.40552, 144.88774

DATABASE_PATH = /g/data/u46/users/pd1813/INSAR/s1_slc_database.db
ORBIT = Descending

ENVISAT_ORBITS=/g/data/dg9/SAR_ORBITS/ENVISAT
ERS_ORBITS=/g/data/dg9/SAR_ORBITS/ERS_ODR_UPDATED
S1_ORBITS=/g/data/fj7/Copernicus/Sentinel-1
POEORB_PATH=/g/data/fj7/Copernicus/Sentinel-1/POEORB
RESORB_PATH=/g/data/fj7/Copernicus/Sentinel-1/RESORB
S1_PATH=/g/data/fj7/Copernicus/Sentinel-1/C-SAR/SLC
PRIMARY_DEM_IMAGE=/g/data/dg9/MASTER_DEM/GAMMA_DEM_SRTM_1as_mosaic.img

JOB_PATH=
OUTPUT_PATH=

# NOTE:
# - the total path to the gamma processing directory will be made up of variables from this file.
# - so, NCI_PATH/PROJECT/SENSOR/GAMMA/TRACK
# - the path needs to exist.

-----PROCESSING OUTPUT DIRECTORIES----------------------------------------------------------------------

SLC_DIR=SLC
DEM_DIR=DEM
INT_DIR=INT
LIST_DIR=lists
RAW_DATA_DIR=raw_data


-----INPUT TEXT FILES-----------------------------------------------------------------------------------

SCENE_LIST=scenes.list
SECONDARY_LIST=slaves.list
IFG_LIST=ifgs.list
    # list for removing scene/s from lists (ie. for SLCs that don't work)
REMOVE_SCENE_LIST=remove_scenes.list


-----PROJECT DIRECTORY & TRACK--------------------------------------------------------------------------

PROJECT=test_project
TRACK=T147D

-----SENSOR DETAILS-------------------------------------------------------------------------------------

    # Polarisation options:
        # ASAR: VV
        # CSK: HH, VV
        # ERS: VV
        # PALSAR1/2: HH, VV, HV, VH (generally HH)
        # RSAT2: HH, VV
        # S1: HH, VV, HV, VH (generally VV)
POLARISATION=VV
    # Options: ASAR, CSK, ERS, JERS1, PALSAR1, PALSAR2, RSAT1, RSAT2, S1, TSX
SENSOR=S1
    # If ERS, specify which one (ERS1 or ERS2)
ERS_SENSOR=
    # If PALSAR2, specify which raw data level (raw or slc)
PALSAR2_TYPE=


-----MULTI-LOOK VALUES----------------------------------------------------------------------------------

    # For full resolution (with square pixels), set to 1
MULTI-LOOK=1
    # Leave as 'auto' if not pre-selecting, it will then be auto calculated and updated
RANGE_LOOKS=auto
AZIMUTH_LOOKS=auto


-----INTERFEROGRAM PROCESSING METHOD--------------------------------------------------------------------

    # Options: chain (use daisy-chain), sbas (use reference master) or single (use single master)
PROCESS_METHOD=single
    # Leave as 'auto' if not pre-selecting a scene, it will then be calculated and updated
REF_PRIMARY_SCENE=20151127
    # thresholds for minimum and maximum number of SBAS connections
MIN_CONNECT=4
    # default is 7 for S1, 10 for other sensors (e.g. RSAT2)
MAX_CONNECT=7
# How many of the latest dates in a stack to include in the SBAS network of appended stacks
# (eg: how many existing dates to link with the new dates being appended)
NUM_LINKED_APPEND_DATES=5

-----PROCESSING STEPS-----------------------------------------------------------------------------------

WORKFLOW=INTERFEROGRAM

# Leave as 'auto' if not pre-selecting a scene, it will then be calculated and updated
# Scene can be different from the PRIMARY_SCENE used in Processing Method
S1_RESIZE_REF_SLC=auto

# Clean up intermediate processing files
CLEANUP=yes


-----DEM COREGISTRATION PARAMETERS----------------------------------------------------------------------

    -----FOR init_offsetm-----
    # Correlation patch size (128, 256, 512, 1024) (default: 1024)
        # Use larger window for large scenes and use scene centre (e.g. S1)
        # Use smaller window for windows towards edge of scene and smaller scenes (e.g. FB PALSAR)
DEM_PATCH_WINDOW=1024
    # Select centre of window for initial offset estimation (default: "-" this gives scene centre)
DEM_RPOS=-
DEM_AZPOS=-

    -----FOR create_diff_par-----
    # Range, azimuth offsets of image2 relative to image1 (samples) (default: 0 0) - for full DEM only, auto calculated for mli
DEM_OFFSET=0 0
    # Enter number of offset measurements in range, azimuth (default: 32 32)
DEM_OFFSET_MEASURE=32 32
    # Search window sizes (32, 64, 128...) in range, azimuth (default: 256 256)
DEM_WIN=256 256
    # Correlation SNR threshold (default: 0.15)
DEM_SNR=0.15
    # If full resolution processing, may need to change 'geocode' rad_max value to 8 to avoid holes in interpolation (default: 4)
DEM_RAD_MAX=4


-----SECONDARY COREGISTRATION PARAMETERS--------------------------------------------------------------------

    # Cross-correlation threshold for offset rejection (default: 0.1)
COREG_CC_THRESH=0.1
    # Number of polynomial model parameters (1, 3, 4 or 6; only 1 required for S1)
COREG_MODEL_PARAMS=1
    # Size of search window for intensity cross-correlation (range, azimuth) (default: 256 256)
COREG_WINDOW_SIZE=256 256
    # Number of search windows in range and azimuth directions (default: 64)
COREG_NUM_WINDOWS=64
    # SLC oversampling factor (1, 2 or 4) (default: 2)
COREG_OVERSAMPLING=2
    # Maximum number of offset estimation iterations (default: 5)
COREG_NUM_ITERATIONS=5

    -----FOR create_diff_par-----
    # Enter number of offset measurements in range, azimuth (default: 32 32)
SECONDARY_OFFSET_MEASURE=32 32
    # Cross-correlation threshold (default: 0.15)
SECONDARY_CC_THRESH=0.15

    -----SENTINEL-1 ONLY-----
    # Coherence threshold used (default: 0.6)
COREG_S1_CC_THRESH=0.6
    # Minimum valid fraction of unwrapped phase values used (default: 0.01)
COREG_S1_FRAC_THRESH=0.01
    # Phase standard deviation threshold (default: 0.8)
COREG_S1_STDEV_THRESH=0.8


-----INTERFEROGRAM PARAMETERS---------------------------------------------------------------------------

IFG_GEOTIFF=yes

    # Coherence threshold for masking
IFG_COHERENCE_THRESHOLD=0.3
    # Mask unwrapped pixels below coherence threshold
IFG_UNW_MASK=no
    # Number of unwrapping patches (default: 1, for high res data may need to be 2 or more)
IFG_PATCHES_RANGE=2
IFG_PATCHES_AZIMUTH=2
IFG_PATCHES_OVERLAP_PX=1024
    # Location of reference pixel
IFG_REF_POINT_RANGE=-
IFG_REF_POINT_AZIMUTH=-

    # Adaptive spectral filtering (adf) parameters
        # Exponent for non-linear filtering
IFG_EXPONENT=0.5
        # Filtering FFT window size (8 - 512, default: 32)
IFG_FILTERING_WINDOW=32
        # Coherence estimation window value (must be odd numbers, default: 3)
IFG_COHERENCE_WINDOW=3
        # Baseline estimation
IFG_ITERATIVE=no
IFG_BASELINE_REFINEMENT=OFF

    -----CSK SPOTLIGHT ONLY-----
    # Cross-correlation threshold (default: 0.15)
IFG_THRES=0.15
    # Window for cross-correlation (larger better, default: 512)
IFG_INIT_WIN=512 512
    # Offset window (recommended to use at least 64)
IFG_OFFSET_WIN=128 128

