##### GAMMA CONFIGURATION FILE #####

-----NCI SOFTWARE CONFIGURATION FILE--------------------------------------------------------------------

GAMMA_CONFIG=/g/data/dg9/SOFTWARE/dg9-apps/GAMMA/GAMMA_CONFIG


-----NCI FILE PATHS-------------------------------------------------------------------------------------

NCI_PATH=/g/data/dz56/mitch-testing/S1/GAMMA
ENVISAT_ORBITS=/g/data/dg9/SAR_ORBITS/ENVISAT
ERS_ORBITS=/g/data/dg9/SAR_ORBITS/ERS_ODR_UPDATED
S1_ORBITS=/g/data/fj7/Copernicus/Sentinel-1
POEORB_PATH=/g/data/fj7/Copernicus/Sentinel-1/POEORB
RESORB_PATH=/g/data/fj7/Copernicus/Sentinel-1/RESORB
S1_PATH=/g/data/fj7/Copernicus/Sentinel-1/C-SAR/SLC

DATABASE_PATH = /g/data/test_database.db
PRIMARY_DEM_IMAGE=/g/data/test_dem_10km.tif

STACK_ID=RSAT_TEST_FRAME
JOB_PATH=
OUTPUT_PATH=

LAND_CENTER=-27, 148.3

-----PROCESSING OUTPUT DIRECTORIES----------------------------------------------------------------------

SLC_DIR=SLC
DEM_DIR=DEM
INT_DIR=INT
BASE_DIR=baselines
LIST_DIR=lists
ERROR_DIR=error_results
RAW_DATA_DIR=RAW_DATA


-----INPUT TEXT FILES-----------------------------------------------------------------------------------

SCENE_LIST=scenes.list
SECONDARY_LIST=slaves.list
IFG_LIST=ifgs.list
FRAME_LIST=frame.list
S1_BURST_LIST=subset_burst.list
S1_DOWNLOAD_LIST=s1_download.list
    # list for removing scene/s from lists (ie. for SLCs that don't work)
REMOVE_SCENE_LIST=remove_scenes.list


-----PROJECT DIRECTORY & TRACK--------------------------------------------------------------------------

PROJECT=mitch-testing
TRACK=NO_TRACK
ORBIT = Descending

-----RAW DATA & DEM LOCATION ON MDSS--------------------------------------------------------------------

    # Sentinel-1 - if AOI within Australia, GAMMA DEM will be produced automatically.
                 - if AOI elsewhere,a  manual GAMMA DEM will need to first be created and MDSS_DEM_tar
                   details required.
                 - data downloaded directly from S1_PATH and S1_ORBITS.

    # Options: aust (within Australia) or other (outside Australia)
DEM_AREA=aust
    # if using DEM from MDSS, enter file name (exc. tar.gz). If auto generated, enter track name
DEM_NAME=__dem_name__
MDSS_DATA_DIR=insar/<sensor>/<project>/<track>
MDSS_DEM_TAR=insar/DEM/<project>/<tar_name>.tar.gz
    # Name of external image used for DEM coregistration (if required, eg. very flat terrain)
EXT_IMAGE=


-----SENSOR DETAILS-------------------------------------------------------------------------------------

    # Polarisation options:
        # ASAR: VV
        # CSK: HH, VV
        # ERS: VV
        # PALSAR1/2: HH, VV, HV, VH (generally HH)
        # RSAT2: HH, VV
        # S1: HH, VV, HV, VH (generally VV)
POLARISATION=HH
    # Options: ASAR, CSK, ERS, JERS1, PALSAR1, PALSAR2, RSAT1, RSAT2, S1, TSX
SENSOR=PALSAR1
    # Sensor mode options:
        # ASAR: I4 or - for other image modes
        # CSK: HI or SP (HIMAGE or Spotlight)
        # PALSAR2: WD or SM (Wide-swath/Stripmap)
        # RSAT2: W or MF (Wide/Multi-look Fine)
        # S1: IWS or SM (Interferometic Wide Swath/Stripmap)
SENSOR_MODE=???
    # If ERS, specify which one (ERS1 or ERS2)
ERS_SENSOR=
    # If PALSAR2, specify which raw data level (raw or slc)
PALSAR2_TYPE=


-----MULTI-LOOK VALUES----------------------------------------------------------------------------------

    # For full resolution (with square pixels), set to 1
MULTI_LOOK=2
    # Leave as 'auto' if not pre-selecting, it will then be auto calculated and updated
RANGE_LOOKS=2
AZIMUTH_LOOKS=4


-----INTERFEROGRAM PROCESSING METHOD--------------------------------------------------------------------

    # Options: chain (use daisy-chain), sbas (use reference master) or single (use single master)
PROCESS_METHOD=sbas
    # Leave as 'auto' if not pre-selecting a scene, it will then be calculated and updated
REF_PRIMARY_SCENE=auto
    # thresholds for minimum and maximum number of SBAS connections
MIN_CONNECT=4
    # default is 7 for S1, 10 for other sensors (e.g. RSAT2)
MAX_CONNECT=7
# How many of the latest dates in a stack to include in the SBAS network of appended stacks
# (eg: how many existing dates to link with the new dates being appended)
NUM_LINKED_APPEND_DATES=5

-----PROCESSING STEPS-----------------------------------------------------------------------------------

WORKFLOW=INTERFEROGRAM
CLEANUP=yes
S1_RESIZE_REF_SLC=auto


-----DEM COREGISTRATION PARAMETERS----------------------------------------------------------------------

    -----FOR init_offsetm-----
    # Correlation patch size (128, 256, 512, 1024) (default: 1024)
        # Use larger window for large scenes and use scene centre (e.g. S1)
        # Use smaller window for windows towards edge of scene and smaller scenes (e.g. FB PALSAR)
DEM_PATCH_WINDOW=1024
    # Select centre of window for initial offset estimation (default: "-" this gives scene centre)
DEM_RPOS=-
DEM_AZPOS=-

    -----FOR create_diff_par-----
    # Range, azimuth offsets of image2 relative to image1 (samples) (default: 0 0) - for full DEM only, auto calculated for mli
DEM_OFFSET=0 0
    # Enter number of offset measurements in range, azimuth (default: 32 32)
DEM_OFFSET_MEASURE=32 32
    # Search window sizes (32, 64, 128...) in range, azimuth (default: 256 256)
DEM_WIN=256 256
    # Correlation SNR threshold (default: 0.15)
DEM_SNR=0.15
    # If full resolution processing, may need to change 'geocode' rad_max value to 8 to avoid holes in interpolation (default: 4)
DEM_RAD_MAX=4


-----SECONDARY COREGISTRATION PARAMETERS--------------------------------------------------------------------

    # Cross-correlation threshold for offset rejection (default: 0.1)
COREG_CC_THRESH=0.1
    # Number of polynomial model parameters (1, 3, 4 or 6; only 1 required for S1)
COREG_MODEL_PARAMS=1
    # Size of window for intensity cross-correlation (default: 128)
COREG_WINDOW_SIZE=128
    # Number of search windows in range and azimuth directions (default: 64)
COREG_NUM_WINDOWS=64
    # SLC oversampling factor (1, 2 or 4) (default: 2)
COREG_OVERSAMPLING=2
    # Maximum number of offset estimation iterations (default: 5)
COREG_NUM_ITERATIONS=5

    -----FOR create_diff_par-----
    # Enter number of offset measurements in range, azimuth (default: 32 32)
SECONDARY_OFFSET_MEASURE=32 32
    # Search window sizes (32, 64, 128...) (range, azimuth) (default: 256 256)
SECONDARY_WIN=256 256
    # Cross-correlation threshold (default: 0.15)
SECONDARY_CC_THRESH=0.15

    -----SENTINEL-1 ONLY-----
    # Coherence threshold used (default: 0.8)
COREG_S1_CC_THRESH=0.7
    # Minimum valid fraction of unwrapped phase values used (default: 0.01)
COREG_S1_FRAC_THRESH=0.01
    # Phase standard deviation threshold (default: 0.8)
COREG_S1_STDEV_THRESH=0.8


-----INTERFEROGRAM PARAMETERS---------------------------------------------------------------------------

IFG_GEOTIFF=yes

    # Coherence threshold for masking
IFG_COHERENCE_THRESHOLD=0.3
    # Mask unwrapped pixels below coherence threshold
IFG_UNW_MASK=no
    # Number of unwrapping patches (default: 1, for high res data may need to be 2 or more)
IFG_PATCHES_RANGE=1
IFG_PATCHES_AZIMUTH=1
IFG_PATCHES_OVERLAP_PX=512
    # Location of reference pixel
IFG_REF_POINT_RANGE=-
IFG_REF_POINT_AZIMUTH=-

    # Adaptive spectral filtering (adf) parameters
        # Exponent for non-linear filtering
IFG_EXPONENT=0.5
        # Filtering FFT window size (8 - 512, default: 32)
IFG_FILTERING_WINDOW=32
        # Coherence estimation window value (must be odd numbers, default: 3)
IFG_COHERENCE_WINDOW=3
        # Baseline estimation
IFG_ITERATIVE=no
IFG_BASELINE_REFINEMENT=OFF

    -----CSK SPOTLIGHT ONLY-----
    # Cross-correlation threshold (default: 0.15)
IFG_THRES=0.15
    # Window for cross-correlation (larger better, default: 512)
IFG_INIT_WIN=512 512
    # Offset window (recommended to use at least 64)
IFG_OFFSET_WIN=128 128


